# Generated by Django 3.1.2 on 2020-10-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201031_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_product',
            field=models.BooleanField(default=False, verbose_name='Лучший продукт(продаваемый)'),
        ),
    ]
