# Generated by Django 3.1.2 on 2020-10-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_best_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/bestproduct/', verbose_name='Изображение'),
        ),
    ]
